### ISSUE TITLE
change order of question search cards

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1224] opened 2017-06-16 15:05 UTC
when you choose related objects - questions on instrument details page: order the question search cards by indexInInstrument not by ID or question number, because e.g. search card of question 1.1 should be followed by search card of question 1.2 not of question 1.10

**Comment by svietgen** [comment] 2017-06-21 11:42
duplicate of #1226

**Closed by svietgen** 2017-06-21 11:42 UTC
Labels: prio:?, type:backlog item
