### ISSUE TITLE
As data provider and as publisher I want to delete all questions and variables with one click

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1902] opened 2018-12-04 12:31 UTC
For variables and questions (excel/json interfaces), I don't know how to delete previously uploaded variables or questions. I do not want to replace them, but just delete them all.

**Comment by rreitmann** [comment] 2018-12-06 12:10
We will add a delete all button to all tabs in the search...

**Comment by rbirkelbach** [comment] 2019-01-16 13:32
I don't see the delete button in the search (ie).

**Comment by rbirkelbach** [comment] 2019-01-17 07:43
I also cannot reproduce it anymore. Weird. I'll close this issue.

**Closed by rbirkelbach** 2019-01-17 07:43 UTC
Labels: category:crosscutting, points:5, prio:1, status:development, type:backlog item
