### ISSUE TITLE
Scrolling down the options of the Select Box is not possible

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1620] opened 2018-04-13 06:28 UTC
When I click on Survey Design on the study edit page and scroll down, I scroll down the page but not the options of the select box.
![md-select_bug](https://user-images.githubusercontent.com/19772575/38719540-ceaae7d8-3ef2-11e8-92c3-a532357a8204.png)

**Comment by rreitmann** [comment] 2018-05-09 15:34
@YPeper Please test this on the dev system...

**Comment by YPeper** [comment] 2018-05-11 07:06
Tested in all four browsers (IE, Edge, FF, Chrome). Bug can no longer be reproduced. 
However, scrolling outside of the select box isn't possible when a select box is open. If intended it is working as it should be. @rreitmann

**Comment by rreitmann** [comment] 2018-05-15 11:16
Scrolling down outside of select boxes, autocompletes, ... when they are open is not possible in angularjs material...

**Comment by rbirkelbach** [comment] 2018-05-17 12:08
Drop area not full screen.

**Comment by rreitmann** [comment] 2018-05-17 13:01
Should be fixed now.

**Closed by rreitmann** 2018-05-17 13:01 UTC
Labels: category:crosscutting, points:5, prio:1, type:bug
