### ISSUE TITLE
Finalize "variable part" of metadataschema for variable report and variable detail page 

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#154] opened 2016-01-10 14:20 UTC
this is a subset of issue #126 which should be finished first. Include all variable properties, which are relevant for Abs2005, Panel2008 and SE19 datasets

**Comment by rreitmann** [comment] 2016-01-12 09:17
Duplicate of #126

**Closed by rreitmann** 2016-01-12 09:17 UTC
Labels: category:crosscutting, prio:1, type:backlog item
