### ISSUE TITLE
Add frequency distributions to variables

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#45] opened 2015-09-11 11:30 UTC
As public user I want to see freequency distributions of variables.

**Comment by dkatzberg** [comment] 2016-02-05 08:17
We will use: http://krispo.github.io/angular-nvd3/#/

**Comment by rreitmann** [comment] 2016-02-24 13:40
@anfranken Please test the variable charts...

**Comment by anfranken** [comment] 2016-03-08 08:07
@dkatzberg: upper frequency distributions is crashed after minimization (IE) ![frequencydistributions](https://cloud.githubusercontent.com/assets/13656277/13595546/8d6b7b94-e50c-11e5-80f0-603b1dab3b75.png)

**Comment by dkatzberg** [comment] 2016-03-11 09:14
The design has no priority. The issue is given by a wrong use of the bootstrap coloumn with two diagramms. This will be fixed by a redesign of the page.

**Closed** 2016-03-11 11:14 UTC
Labels: category:variablemanagement, points:8, prio:1, type:backlog item
