### ISSUE TITLE
Version of data package on test system is corrupted?

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#3251] opened 2023-10-18 14:53 UTC
https://test.metadata.fdz.dzhw.eu/de/projects/gra2009?tab=versions

On test, I can't order the first version of the data package of gra2009
![grafik](https://github.com/dzhw/metadatamanagement/assets/18573122/161b1cd0-d17c-4e9a-882e-b872cc8e0275)

In the project overview, the version seems corruptes
![grafik](https://github.com/dzhw/metadatamanagement/assets/18573122/6db5cfda-4a68-4e66-963b-b29e323a3f76)

**Comment by tilovillwock** [comment] 2023-11-06 13:53
@UteH this has been fixed by @moellerth.

According to her research the data acquisition project lacked the attributes `released`, `hasBeenReleasedBefore` and `hidden` which in our understanding is inconsistent with the fact that it already had two version entries (a version entry is connected to a release, `hidden` defaults to `false`, etc).

The attributes have been added manually, the dataset was reindexed and the issue seems to be **resolved for now**. Some further code research didn't reveal any particular workflow that would cause a project dataset to be malformed like this, which is curious. The only theory @moellerth could come up with was this: the newer dataset version in order had a lesser version value than the old one. Maybe this caused an unexpected logic error in an older application version. We were however unable to reproduce the issue and after talking to @AndyDaniel1 we agreed to table this for now.

**Closed** 2023-11-06 13:54 UTC
Labels: type:backlog item, prio:1, CM23
